# Habilitar la consola
#spring.h2.console.enabled=true

# Ruta de acceso (opcional, por defecto es /h2-console)
#spring.h2.console.path=/h2-console

# Configuración recomendada para evitar problemas de conexión
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

# --- Configuración MySQL en EC2 (Localhost) ---

# URL: localhost porque la app y la BD viven en el mismo servidor EC2
spring.datasource.url=jdbc:mysql://localhost:3306/nance_db

# Las credenciales que creaste en el PASO 2
spring.datasource.username=*
spring.datasource.password=*

# Driver y Dialecto
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Mantiene las tablas actualizadas (cuidado en producción real)
spring.jpa.hibernate.ddl-auto=update